export const ADD_THEME_REQUEST = 'ADD_THEME_REQUEST';
export const  ADD_THEME_SUCCESS = 'ADD_THEME_SUCCESS';
export const  ADD_THEME_ERROR = 'ADD_THEME_ERROR';
export const OPEN_THEMES = 'OPEN_THEMES';
export const CLOSE_THEMES = 'CLOSE_THEMES';

export const ADD_COMMIT_REQUEST = 'ADD_COMMIT_REQUEST';
export const  ADD_COMMIT_SUCCESS = 'ADD_COMMIT_SUCCESS';
export const ADD_COMMIT_ERROR = 'ADD_COMMIT_ERROR';